server:
  port: 9000
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
      
info:
  app:
    name: API Gateway
    description: API Gateway for Microservices
    version: 1.0.0
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
        type: rabbit
    rabbitmq:
      queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
          
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO