server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
      
info:
  app:
    name: Organization Microservice
    description: Microservice containing services related to Organization, Practice and Doctor
    version: 1.0.0
    
services:
  patient:
    baseUrl: http://localhost:8080
    createPatientUrl: /api/v1/patient

resilience4j:
  circuitbreaker:
    instances:
      practiceControllerListPatientsByPractice: 
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 2
      doctorControllerListPatientsByDoctor: 
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 2       