server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
      
info:
  app:
    name: Patient Microservice
    description: Microservice containing services related to Patient
    version: 1.0.0
    
resilience4j:
  circuitbreaker:
    instances:
      patientControllerGetDoctor: 
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 2
      patientControllerGetPractice: 
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 2
        
logging:
  level: 
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG 